name: Git Commits Since Release
description: git action that retrieves git commits since the last release
author: dkhunt27

branding:
  icon: command
  color: blue

runs:
  using: node24
  main: dist/index.js
